### ISSUE TITLE
simple-ops set does not work for config paths that do not exist

### ISSUE THREAD

**Issue by richardjennings** [richardjennings/simple-ops#11]
The set command does not work for config paths that do not exist. For example config/some.yml
```yaml
chart: thing-1.1.1.tgz
deploy:
  example:
    values:
```

```simple-ops set some.deploy.example.values.foo bar ``` does not work

Support for lists using a numeric value in the config path is only functional in limited use cases.
