### ISSUE TITLE
chaining of operations

### ISSUE THREAD

**Issue by richardjennings** [richardjennings/simple-ops#25]
The flow of operations is currently Helm => SO => Kustomize Inline, Jsonnet.
The Kustomization functionality currently only applies inline to previously generated output (from Helm).
There are currently intermediate steps between Helm and Kustomize that provide simple-ops labelling and namespace shortcuts.
Jsonnet is appended to the output of Kustomize (if any) on Helm (if any).
To better expand the ways simple-ops can be used, a configuration mechanism to configure the way operations are chained together is needed. This potentially can include linting and auditing in the future.

Using the current config merging approach, a top-level "chain" config would apply by default to all deploy configurations and could be overridden per deploy. This could be specified in simple-ops.yaml by default. E.g.

```yaml
chain:
  helm:
  kustomize_file:
  jsonnet_file:
  jsonnet_inline:
  so-namespace:
  so-labels:
  kustomize_inline:
```
